number = int(input("Введите число от 1 до 10:" )) #Вводим число, которое надо будет посчитать
if number <= 0 or number > 10: #Вводим ограничения по вводимым числам (можно только от 1 до 10)
    print("Число не то!")
print(number, "* 1 =", number * 1)
print(number, "* 2 =", number * 2)
print(number, "* 3 =", number * 3)
print(number, "* 4 =", number * 4)
print(number, "* 5 =", number * 5)
print(number, "* 6 =", number * 6)
print(number, "* 7 =", number * 7)
print(number, "* 8 =", number * 8)
print(number, "* 9 =", number * 9)
print(number, "* 10 =", number * 10) #И очень запутанным способом (избейте меня) выводим каждое вычисление))
